name: Continuous Integration

on:
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.1]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: yarn install
      - name: Lint
        run: yarn lerna run --parallel lint
      - name: Build
        run: yarn lerna run --parallel build
