name: Continuous Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write

jobs:
  buildAndDeploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.14.2]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: yarn install
      - name: Build
        run: yarn lerna run --parallel build-doc
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
      - name: Get commit message
        id: commit_message
        run: |
          commit_message=$(git log --format=%B -n 1 ${{ github.sha }})
          echo "commit_message=$commit_message" >> $GITHUB_OUTPUT
      - name: Get repository name
        id: extracted_name
        run: |
          repository_name=${{ github.repository }}
          extracted_name=$(echo $repository_name | cut -d '/' -f 2)
          echo "extracted_name=$extracted_name" >> $GITHUB_OUTPUT
      - name: Send deployment information to Waroom
        run: |
          curl --location --request POST 'https://api.staging.waroom.com/v1/organizations/topotal/services/waroom-frontend-prod/deployments' \
            --header 'Content-Type: application/json' \
            --header 'Accept: application/json' \
            --header 'Authorization: Bearer AtVvle8ZOTwVDNw1BsKY_R2QB3K_VPNE5E1tAcTKpJ4' \
            --data-raw '{
              "ref": ${{ github.sha }},
              "environment": "Production",
              "platform": "github",
              "description": ${{ steps.commit_message.outputs.commit_message }},
              "repository_owner": ${{ github.repository_owner }},
              "repository_name": ${{ steps.extracted_name.outputs.extracted_name }}
            }'
